### ISSUE TITLE
Plugin not working anymore (after website update?) 

### ISSUE THREAD

**Issue by eNBeWe** [cccc/plugin.video.media-ccc-de#1]
Starting today, the Plugin comes up with an empty listing when starting to search for videos. I suppose it has to do with the technical overhaul, that was announced today.

**Comment by manno** [comment]
I accidentially removed `webgen_location` from the JSON api. I just added it back, does that help?

**Comment by eNBeWe** [comment]
Hi,
yes everything is fine again, thanks.
