### ISSUE TITLE
Offer three stills as preview

### ISSUE THREAD

**Issue by PanderMusubi** [cccc/plugin.video.media-ccc-de#18]
Please offer three stills as preview with automatically showing the next still after e.g. 1 second. Some talks are difficult to find back by the current (title and) only one still. Also a single still preview is sometimes even in combination with the title) too limited to get a good impression of a talk.

**Comment by TobiX** [comment]
More meta info is provided if you switch to a different view¹ (or use the "Info"/ I button).

I'm not a fan of animated video previews (as we had on the first iteration of media.ccc.de), it makes the browsing view really twitchy... (And I don't even know if Kodi supports animated previews)

¹ Kodi 17 default skin:
![Kodi 17 screenshot](https://cloud.githubusercontent.com/assets/78534/21948873/29a116a0-d9ee-11e6-9c98-41fede928355.png)

**Comment by PanderMusubi** [comment]
Thank you for the exta info.
