### ISSUE TITLE
streaming is not working on openelec v 6.0.0 with an raspberry pi 1 and kodi (isengard, v 16?)?

### ISSUE THREAD

**Issue by stevleibelt** [cccc/plugin.video.media-ccc-de#2]
Hey,

pretty hard to say why it is not working.
Following the output of the logfile when I hit "ok" on "halle 1" (the location does not matter). Logging was enabled for FFMPEG, Video and Network.

```
23:53:06 412.837982 T:1679815744   DEBUG: Previous line repeats 7 times.
23:53:06 412.838348 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Input.Select
23:53:07 413.263977 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Player.GetActivePlayers
23:53:09 416.116425 T:1688204352   DEBUG: Previous line repeats 2 times.
23:53:09 416.116913 T:1688204352   DEBUG: Thread JobWorker 1688204352 terminating (autodelete)
23:53:10 416.299866 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Player.GetActivePlayers
23:53:19 425.769562 T:1618998336   DEBUG: Previous line repeats 9 times.
23:53:19 425.769897 T:1618998336   DEBUG: Thread JobWorker 1618998336 terminating (autodelete)
23:53:20 426.404449 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Player.GetActivePlayers
23:54:01 467.451691 T:1793352768   DEBUG: Previous line repeats 40 times.
23:54:01 467.452057 T:1793352768   DEBUG: ### [Qlock] - Delaying 240 secs
23:54:01 467.794556 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Player.GetActivePlayers
23:58:00 707.108154 T:1679815744   DEBUG: Previous line repeats 138 times.
23:58:00 707.108582 T:1679815744   DEBUG: webserver: request received for /jsonrpc?Input.Home
23:58:00 707.110291 T:1967439872   DEBUG: Activating window ID: 10000
23:58:01 707.506775 T:1618998336   DEBUG: webserver: request received for /jsonrpc?Player.GetActivePlayers
```

Hope this helps. Since the congress takes only four days, we are a bit in hurry for getting useful log files.

And by the way, streaming is working well on my laptop in the same network.

Anyway, thanks so far for this great add on :-).

**Comment by TobiX** [comment]
Could you try to get better log files? http://kodi.wiki/view/Log_file/Easy has a guide... Did you try switching formats/quality?

**Comment by stevleibelt** [comment]
Yep, switched formats and quality. I will try the rest tomorrow or on day four.
Is it working with the same setup on one of your machines?
Thanks for the quick response.

**Comment by stevleibelt** [comment]
@TobiX 
have a look on my [uploaded log](http://xbmclogs.com/plduoanrn#line-780).

Kind regards

**Comment by TobiX** [comment]
Nothing apparent there, I'm afraid :(

But I'm a bit concerned about this:

````
17:14:27  73.570198 T:1627808832   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
17:14:27  73.571648 T:1627808832   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
````

Maybe more of OpenELECs TLS support is broken? (streaming.)media.ccc.de has a quite modern TLS setup...

**Comment by stevleibelt** [comment]
@TobiX 

I've created an [issue](https://github.com/OpenELEC/OpenELEC.tv/issues/4555)-ticket on the openelec project for that. Lets see.

**Comment by TobiX** [comment]
@stevleibelt There is currently an active stream on streaming.media.ccc.de - Can you retest?

**Comment by myoung34** [comment]
Anyone have any workarounds? I'm still affected.

**Comment by stevleibelt** [comment]
@TobiX,

sorry, I'm pretty busy right now. I will give it a test on the upcoming weekend if possible.
Sorry I missed the current stream 16 days ago. Time is passing by so fast at the moment :-(.

**Comment by derchrisuk** [comment]
I have the TLS/SSL error regarding the SNI extension on my Fire TV as well.
Tried it with the latest EH16 videos, all of them are not playable throwing the exact same error.
Actually, all videos looks like they are not playing anymore.

**Comment by derchrisuk** [comment]
Looks like there was a pending update. Now with 0.0.5 all seems to work again.

**Comment by stevleibelt** [comment]
Hey, @darthrake 

Is ist working for the 33c3?
I didn't had the chance to buy a ticket so streamling is my only way to get my congress feeling.
I am using version 0.0.5 and it is not working.

**Comment by dekarl** [comment]
As the issue has been reported to also happen on the FireTV I'm happy to confirm that 0.0.5 is working for live streaming from the 33c3 on FireTV right now.

**Comment by stevleibelt** [comment]
@dekarl 

Thanks for your quick response. To bad it is not working on my raspberry pi 1 with openelec v 6.0.3 (default settings everywhere).

**Comment by kenzodeluxe** [comment]
I think it won't work for your and my version of (Libre|Open)ELEC:
```
11:38:34 T:545695756512   ERROR: ffmpeg[7F0E0070E0]: [tls] Unable to negotiate TLS/SSL session
11:38:34 T:545695756512   DEBUG: Error, could not open file https://cdn.c3voc.de/hls/s1_native_sd.m3u8
```
However according to https://libreelec.tv/2016/10/libreelec-krypton-v7-90-008-alpha/, all versions since October should work (**Fix ffmpeg issues connecting to TLS 1.2 streams**).

**Comment by stevleibelt** [comment]
@kenzodeluxe 

thanks for the information, even if it is a not so good one for us both.

**Comment by TobiX** [comment]
Unfortunatly, this is only fixed in the LibreElec ALPHA releases, LibreElec 7.0.2 can't open our streams. I'll try to implement a wrokaround.

**Comment by stevleibelt** [comment]
I've just downloaded the latest [osmc.tv](https://osmc.tv/download/) image for the pi, installed it as well as your plugin and it is working so far.
Now I only need to configure this thing et volia. Finally I can say thank your for your work @TobiX :-).

**Comment by TobiX** [comment]
I added an option to disable TLS, please try the addon from http://is.gd/ccckodi
