### ISSUE TITLE
Items in subolder inside category are not accessible

### ISSUE THREAD

**Issue by derchrisuk** [cccc/plugin.video.media-ccc-de#5]
While I was browsing through the conferences category, I discovered an issue with access certain items.
For example trying to get to Nixcon, I get the following error:

    01:29:27 T:1087164040   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.media-ccc-de/dir/conferences/nixcon
    01:29:27 T:1087164040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.media-ccc-de/dir/conferences/nixcon) failed
    01:29:34 T:1548951752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'routing.RoutingError'>
                                            Error Contents: No route to path "/dir/conferences/vcfb"
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.media-ccc-de/addon.py", line 167, in <module>
                                                plugin.run()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.routing/lib/routing.py", line 122, in _dispatch
                                                raise RoutingError('No route to path "%s"' % path)
                                            RoutingError: No route to path "/dir/conferences/vcfb"
                                            -->End of Python script error report<--

It looks like all items, which are in a subfolder, are not accessible.
Tested it with all the other which have a subfolder, and I could not open any of them.
I have not tested if there are any other areas where this might be a problem.

This is on a FireTV with latest Kodi 16-Beta5

**Comment by TobiX** [comment]
Fixed in development version, please try http://is.gd/ccckodi
